# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Assess' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Assess
  pod 'PaginatedTableView'
  pod 'SDWebImage', '~> 5.0'

  target 'AssessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AssessUITests' do
    # Pods for testing
  end

end
